# Generated by Django 2.1.7 on 2019-04-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190412_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.TextField(default=''),
        ),
    ]
