# Generated by Django 2.1.7 on 2019-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='democontent',
            field=models.FilePathField(blank=True, default='', null=True, path='/demo'),
        ),
    ]
