# Generated by Django 2.2.4 on 2019-08-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_democontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='importance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
