# Generated by Django 2.2.4 on 2019-08-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
