# Generated by Django 2.1.7 on 2019-04-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cover', models.FilePathField(blank=True, default='', null=True, path='/img')),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
