# Generated by Django 2.1.7 on 2019-04-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_number',
            new_name='index',
        ),
    ]
