# Generated by Django 2.1.7 on 2019-04-14 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
