# Generated by Django 2.1.7 on 2019-04-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blurb',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
