# Generated by Django 2.1.7 on 2019-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_credit',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
