# Generated by Django 2.1.7 on 2019-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_cover_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FilePathField(blank=True, default='', null=True, path='/posts'),
        ),
    ]
